define(function () {
    return [
        { romaji: "Eki", kana: "えき", english: "Train station" },
        { romaji: "Basu‐tei", kana: "バスてい", english: "Bus stop" },
        { romaji: "Kouen", kana: "こうえん", english: "Park" },
        { romaji: "Hoteru", kana: "ホテル", english: "Hotel" },
        { romaji: "Resutoran", kana: "レストラン", english: "Restaurant" },
        { romaji: "Koban", kana: "こうばん", english: "Police boxes" },
        { romaji: "Depato", kana: "デパート", english: "Department Store" },
        { romaji: "Bijutsukan", kana: "びじゅつかん", english: "Art Museum" },
        { romaji: "Hakubutsukan", kana: "はくぶつかん", english: "Museum" },
        { romaji: "Suizokukan", kana: "すいぞくかん", english: "Aquarium" },
        { romaji: "Toshokan", kana: "としょかん", english: "Library" },
        { romaji: "Byouin", kana: "びょういん", english: "Hospital" },
        { romaji: "Yuenchi", kana: "ゆうえんち", english: "Amusement park" },
        { romaji: "Dobutsuen", kana: "どうぶつえん", english: "Zoo" },
        { romaji: "Kaisuiyokujo", kana: "かいすいよくじょう", english: "Beach" },
        { romaji: "Toire", kana: "トイレ", english: "Toilet" },
        { romaji: "Yubinkyoku", kana: "ゆうびんきょく", english: "Post Office" },
        { romaji: "Ginko", kana: "ぎんこう", english: "Bank" },
        { romaji: "Shiyakusho", kana: "しやくしょ", english: "City hall" },
        { romaji: "Yakuba", kana: "やくば", english: "Town hall" },
        { romaji: "Gakko", kana: "がっこう", english: "School" },
        { romaji: "Yochien", kana: "ようちえん", english: "Kindergarten" },
        { romaji: "Shogakko", kana: "しょうがっこう", english: "Elementary school" },
        { romaji: "Chugakko", kana: "ちゅうがっこう", english: "Middle school,Junior high" },
        { romaji: "Koko/Kotogakko", kana: "こうこう/こうとうがっこう", english: "High school" },
        { romaji: "Daigaku", kana: "だいがく", english: "University, College" },
        { romaji: "Shotengai", kana: "しょうてんがい", english: "Shopping street" },
        { romaji: "Supa", kana: "スーパー", english: "Grocery store, Super market" },
        { romaji: "Yaoya", kana: "やおや", english: "Vegetable and fruit store" },
        { romaji: "Sakanaya", kana: "さかなや", english: "Fish store" },
        { romaji: "Tokoya", kana: "とこや", english: "Barbershop" },
        { romaji: "Biyouin", kana: "びよういん", english: "Hair salon" },
        { romaji: "Yakkyoku/ Kusuriya", kana: "やっきょく/くすりや", english: "Pharmacy" },
        { romaji: "Ryokan", kana: "りょかん", english: "Japanese style hotel/inn" },
        { romaji: "Otera", kana: "おてら", english: "Buddhist temple" },
        { romaji: "Jinja", kana: "じんじゃ", english: "Shinto Shrine" },
        { romaji: "Kuko", kana: "くうこう", english: "Airport" },
        { romaji: "Minato", kana: "みなと", english: "Harbor/Seaport" }
    ]
})