define(function () {
    return [
        { romaji: "Kaimono", kana: "かいもの", english: "Shopping" },
        { romaji: "Fuku", kana: "ふく", english: "Clothes" },
        { romaji: "Shatsu", kana: "シャツ", english: "Shirt" },
        { romaji: "Zubon", kana: "ズボン", english: "Pants" },
        { romaji: "Kutsu", kana: "くつ", english: "Shoes" },
        { romaji: "Boshi", kana: "ぼうし", english: "Hat" },
        { romaji: "Kutsushita", kana: "くつした", english: "Socks" },
        { romaji: "Sukato", kana: "スカート", english: "Skirt" },
        { romaji: "Wanpisu", kana: "ワンピース", english: "One-piece dress" },
        { romaji: "Nekutai", kana: "ネクタイ", english: "Neck tie" },
        { romaji: "Sebiro", kana: "せびろ", english: "Suit" },
        { romaji: "Beruto", kana: "ベルト", english: "Belt" },
        { romaji: "Jinzu", kana: "ジーンズ", english: "Jeans" },
        { romaji: "Terebi", kana: "テレビ", english: "TV set" },
        { romaji: "Rajio", kana: "ラジオ", english: "Radio" },
        { romaji: "Pasokon", kana: "パソコン", english: "Personal Computer" },
        { romaji: "Kamera", kana: "カメラ", english: "Camera" },
        { romaji: "Teburu", kana: "テーブル", english: "Table" },
        { romaji: "Tsukue", kana: "つくえ", english: "Desk" },
        { romaji: "Sofa", kana: "ソファ", english: "Sofa" },
        { romaji: "Isu", kana: "いす", english: "Chair" },
        { romaji: "Tokei", kana: "とけい", english: "Watch/Clock" },
        { romaji: "Udedokei", kana: "うでどけい", english: "Watch" },
        { romaji: "Keitai (Denwa)", kana: "けいたい(でんわ)", english: "Mobile (Phone)" },
        { romaji: "Kasa", kana: "かさ", english: "Umbrella" },
        { romaji: "Hon", kana: "ほん", english: "Book" },
        { romaji: "Pen", kana: "ペン", english: "Pen" },
        { romaji: "Noto", kana: "ノート", english: "Notebook" },
        { romaji: "Denimu", kana: "デニム", english: "Denim" },
        { romaji: "Kami", kana: "かみ", english: "Paper" },
        { romaji: "Utsuwa", kana: "うつわ", english: "Bowl" },
        { romaji: "Mizu", kana: "みず", english: "Water" },
        { romaji: "(O)Hashi", kana: "(お)はし", english: "Chopsticks" },
        { romaji: "Saifu", kana: "さいふ", english: "Purse" },
        { romaji: "Kaban/Bakku", kana: "かばん/バッグ", english: "Bag" },
        { romaji: "Ryukkusakku", kana: "リュックサック", english: "Backpack" },
        { romaji: "(O)Shibori", kana: "おしぼり", english: "Wet hand-towel" },
        { romaji: "Fukuro", kana: "ふくろ", english: "Shopping Bag" },
        { romaji: "Zasshi", kana: "ざっし", english: "Magazine" },
        { romaji: "Ikura", kana: "いくら", english: "How much?" },
        { romaji: "Nedan", kana: "ねだん", english: "Price" },
        { romaji: "Okane", kana: "おかね", english: "Money" }
    ]
})